### ISSUE TITLE
concept of "line"

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#10]
Needs only to have 4 fields: a name, an extended description, a gene name, and an auto-name tag, for use in generating the names of cages, litters, and mice that are part of this line. If it has the JSON field option, then we can also add the Jax number where appropriate.

When cages, litters, or mice are selected to be part of a line, if they do not yet have a manually typed name, then they are given an automatically generated one based on the tag.

**Comment by nsteinme** [comment]
Actually also needs a "Gene name", in addition to the above.

**Comment by rossant** [comment]
mail by @nsteinme :

1) Create new cage
2) Choose which line (e.g. "AI95") the cage belongs to (at this point the cage name, if it has not been typed manually, auto-fills with sequentially-generated name based on the chosen line name like "AI95_C_0001" (C for cage), which is what can be written on the outside of the cage by Charu or Laura)
3) Add two mice to the cage. When you go to select which mice you're adding to the cage, by default, because you've selected the line, you're now only seeing the mice that are already part of that line (plus the usual green plus button to create a new subject).

-- now, done, you've established a breeding pair. then later, after they produce pups:

4) Go to the page for that cage, and add a litter to it. The mother and father fields auto-fill based on the mice that were in the cage, and the name auto-fills too ("AI95_L_0001"). 
5) Go to the litter page and add a subject to the litter. The nickname of the subject is auto-generated ("AI95_0001" <- "subject" implied in this name for brevity). It will be later changed to something else by the experimenter who uses it, e.g. sylvia would replace it with "SS07548" or whatever. The species, litter, strain, and cage all auto-fill. The only things to enter now about the subject are: its gender, its earmark, and its zygosities. 

Note that there are several things in addition to merely implementing this idea of the line that need to happen to make this work, e.g. currently you cannot add a mouse to a cage from the cage page, instead you have to go to the mouse's page and pick the cage that it goes in. This is equally sensible if you're putting just one mouse in the cage, but if you're putting two mice in, it becomes twice as fast to do it from the cage page, and more logical.

**Comment by rossant** [comment]
I'll create a new `Line` model and add a new `Line` ForeignField to Cage, Subject, and Litter.

### New Cage

* Select Line
* Autofill cage name
* Add mother/father with dropdown (filter with line)
    * http://stackoverflow.com/a/23337009/1595060
    * http://stackoverflow.com/a/8818880/1595060

### New Litter

* Select Cage
* Autofill mother father (two mice in the cage) and name from the Line
* Add subject and autofill subject's fields

**Comment by rossant** [comment]
```python
class Line(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    gene_name = models.CharField(max_length=1023)
    auto_name = models.SlugField(max_length=255)
```

@nsteinme I was unsure about the field types and max length, does that look sensible?

**Comment by nsteinme** [comment]
I don't know what a SlugField is, but otherwise I think this looks good!

**Comment by rossant** [comment]
Mostly done, will need to tweak how mother/father are represented in a litter.
