### ISSUE TITLE
Compatibility with Datajoint

### ISSUE THREAD

**Issue by kdharris101** [cortex-lab/alyx#116]
Hi all,

Some thoughts on how we might bring about compatibility of Alyx with Datajoint. This isn’t a suggestion for anything to do right now, just food for thought for the medium term.

Alyx and Datajoint were designed for different things. 

Alyx was designed to be a user-friendly interface for lab management and for keeping track of what data files are where. For this, the web interface is critical, which is helped by the use of Django and REST APIs. 

Datajoint was designed to make it easy for users to run arbitrary database queries from matlab and python, without needing to learn SQL. Here Django is not an advantage, and users won’t want to write a new REST API every time they have a new query to run. 

If we can make them work together, that would keep the advantages of both. Also, because Datajoint is gaining momentum in the community, compatibility will be important if we want people to use Alyx beyond our own lab. 

A solution could be to use Alyx for standard lab procedures that are not going to change often: for example, maintaining  colonies, performing recordings, doing weighings, as well as standard data analyses such as spike sorting. But to also make it possible for users to query the database using Datajoint, when they want to run ad-hoc data analyses.

As I understand it there are two main barriers to compatibility:

1.	Datajoint uses hierarchical composite primary keys, Alyx uses UUID  keys.
2.	Datajoint uses MySQL, Alyx uses PostreSQL.

Both of these may be solvable. 

(1)	We maintain a set of “Alyx tables” that have both UUID keys and hierarchical composite keys. We can keep the UUID keys as primary, presumably datajoint will be able to execute queries using the hierarchical composite keys even if they are not primary. We let datajoint create its own tables. Alyx can’t access them but this doesn’t matter: it only matters that datajoint can access Alyx’s tables.

(2)	I think I remember hearing that datajoint can use postgres. We should check. But if not, how much of a problem is it for to change Alyx to MySQL? I think MySQL has json fields for example.

**Comment by nsteinme** [comment]
Compatability with IBL/others is a worthy goal - let's figure out for real how many labs are using it? Did you know that Chris advertised in his deepmind interview talk that four labs use Signals? I inquired, it was: carandini lab, saleem lab, haider lab, and benucci lab - and it was only true for half the people in one of those labs. It is telling that we thought Xaq used it and actually he doesn't. 

I tried to read datajoint documentation a while ago and did not understand what's going on. On Sunday afternoon I learned SQL and feel confident I can do basically anything I want to do in it (including from matlab, see my example function [here](https://github.com/cortex-lab/alyx-matlab/blob/master/exampleSQLquery.m)). It's really not very difficult. So I went back to datajoint documentation expecting to now be able to understand it. But I still can't. It is possible, or seems to me even probable, that it is not easier than SQL. It is possible they have invented this really great thing called a wheel, it has so many sides so that it rolls so easily, you're not going to believe how many sides it has, it's got 22 sides, so many sides. 

The auto-computation thing is a fine idea and doesn't come with alyx or postgresql, of course -- but they didn't invent that either - see https://www.ovation.io/ - and actually, really see ovation.io which is a serious company that's been around for quite a while and appears to be doing really well, was developed by a neuroscientist from Adrienne Fairhall's lab. 

Obviously after committing a fair bit of time to alyx over the last few weeks I am becoming quite biased in favor of it! In any case, no reason not to think about compatibility. This whole post of mine is a bit off topic, sorry.

**Comment by kdharris101** [comment]
Thanks!

Xaq in the meantime said Laura Busse has been using datajoint. We should talk to her.

I didn’t know about ovation, it does look interesting. For IBL, it is pretty much agreed there will be some sort of relational database system, but no decision has been made on which one. Datajoint is the one most people have heard of so it presently has the most mindshare. But it isn’t the only possibility.

**Comment by rossant** [comment]
Just a quick comment: if we switch to MySQL, we should do it ASAP before anyone uses the database. I suspect migrating a production database from postgresql to mysql is going to be a pain and I wouldn't be surprised if there are a million little things that will break (we're using postgres-specific features in django).

**Comment by nippoo** [comment]
Closing for the moment so we can focus on current tasks. Let's reopen if we have any strong change of heart.
