### ISSUE TITLE
Try migration to MySQL

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#120]

**Comment by rossant** [comment]
@kdharris101 @nsteinme @nippoo see https://www.reddit.com/r/Python/comments/wg1qa/postgresql_or_mysql_for_django/c5dnobn/

**Comment by nippoo** [comment]
Sorry, very limited internet now, but: I'd steer way clear of MySQL if we can avoid it. I'd much rather investigate the required development to port DataJoint to Postgres or at least add compatibility that way around. MySQL was cool a decade ago and is now mainly around for legacy reasons / because people were used to it. There aren't a great deal of advantages to it nowadays...

**Comment by rossant** [comment]
It seems to me that MySQL is strictly inferior to Postgresql. I agree with Max that we should seriously investigate how complicated it would be to have datajoint support postgresql...

**Comment by kdharris101** [comment]
This is what Dimitri said when I asked:

Currently, DataJoint relies on MySQL-specific low-level interface libraries (pymysql for Python and mym for MATLAB).  Some development would be needed to extend the support to other backends, probably a few weeks. However, we have not yet found a compelling case.

If we do decide to support another database backend, the code that uses DataJoint will remain compatible: all the changes would be contained within the DataJoint library itself.  There is little risk in proceeding with MySQL now and extending to other backends afterwards when or if necessary.

One direction we are considering is to create our own server which would accept datajoint queries directly, without the intermediate compilation to SQL.  This would facilitate extending datajoint to other languages beyond MATLAB and Python.
So, they can do it, but I assume will only do so when they get requests from multiple users.

Feedback from Laura Busse (who currently uses datajoint) is that she is very happy with datajoint, but what it is lacking is something like Alyx, that makes inputting metadata easy. (Currently they have a script to read from excel spreadsheets filled in by hand.) She was very interested in Alyx and offered to beta test.

From this, it seems like there will be users who want to use both. So we have two options:


1.       Continue with Postgres, try to persuade Dimitri to switch when we have a working system.

2.       Write in a way that could use either DB engine. (If possible.)

Agreed that MySQL may be inferior to Postgres – but what are the practical hits we would take by using it?

**Comment by rossant** [comment]
> but what are the practical hits we would take by using it?

* There are no ArrayField so we have to find another solution for those fields (JSON).
* Apparently, changing anything in the schema of a model requires recreating the entire table, which is orders of magnitude longer than in postgres. I don't know how much of a problem it would be for us in practice.
* We can run Python code in postgres SQL queries but not in MySQL. I think it's better if we can avoid using this feature anyway.
* It looks like there are more bugs and hacks in MySQL. Some people using MySQL are hitting so many bugs that they eventually switch to postgresql, whereas migrations in the other way around do not exist. postgres is just a more solid piece of software. We don't know yet if this is going to be a problem in practice... I suspect we'll know once everyone is using the database!

**Comment by kdharris101** [comment]
Ø  There are no ArrayField so we have to find another solution for those fields (JSON).
I guess this in itself an issue for datajoint compatibility: even if they switch datajoint to Postgres, it won’t be able to query anything with an ArrayField. (Perhaps any JSON field also).

Ø  Apparently, changing anything in the schema of a model requires recreating the entire table, which is orders of magnitude longer than in postgres. I don't know how much of a problem it would be for us in practice.
I imagine this will be very rare.

Ø  We can run Python code in postgres SQL queries but not in MySQL. I think it's better if we can avoid using this feature anyway.
Agreed, this sounds dangerous.

Ø  It looks like there are more bugs and hacks in MySQL. Some people using MySQL are hitting so many bugs that they eventually switch to postgresql, whereas migrations in the other way around do not exist. postgres is just a more solid piece of software. We don't know yet if this is going to be a problem in practice... I suspect we'll know once everyone is using the database!
Which means that maybe they will want to switch datajoint over to postgres in any case. (Although I suppose if they had encountered problems they would already be thinking of this.)
Because a good GUI is something missing from DataJoint, and because it is something their users will want, it may be that if we show them Alyx working nicely that will already be enough of a reason for them to support Postgres.
Why don’t we plan on giving Dimitri a demo of Alyx. Will everything be ready to do this sometime next week?

**Comment by nsteinme** [comment]
I think giving a demo will be stronger when we have rolled it out, both
because we'll have found all the bugs, plus because we can say that we've
actually rolled it out. I don't think you're likely to be able to give a
100% convincing demo right now.

**Comment by nippoo** [comment]
Result of discussion: think we should shelve this idea for a few weeks until we've got a stable product. Also worth noting that JSON support in MySQL currently requires a third-party library, http://django-mysql.readthedocs.io/en/latest/model_fields/json_field.html so, in the interests of minimising third-party dependencies, if we *do* have to switch I'd be tempted to leave it until this is natively supported in Django.

**Comment by nippoo** [comment]
Reopened for clarity. It's unclear whether we'll do this one at all though. Hopeful plan is to stick with Postgres and encourage DJ migratIon too, so let's re-evaluate this in a few weeks.

I would recommend reading this Quora thread before putting in the time to migrate... https://www.quora.com/What-are-pros-and-cons-of-PostgreSQL-and-MySQL

**Comment by nippoo** [comment]
I'm going to close this for the moment. Let's reopen if/when we feel we need to.
