### ISSUE TITLE
add more than one subject at a time from subject inline on litter page

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#179]
If you, for example, change gender of the first empty inline, then click "add another subject" before clicking save, then change the gender of that new one, then click save, you get an error about a duplicate nickname (presumably because they are both "-"). If it's not possible to solve this, it isn't the end of the world, it's just annoying to change one, save, change another, save, etc - litters have up to 10 mice in them. 

Ideally this would have a "workflow"-ish option where you could just pick the breeding pair from a dropdown, then type in how many males and how many females and it just creates them all. But I don't see an obvious way to do that in the admin interface.

**Comment by rossant** [comment]
Looks like a bug! It should just work, I'll have a look.

**Comment by rossant** [comment]
Hmm, it's a bit tricky. I've enabled the `unique` constraint on several fields, including `nickname`, to enforce uniqueness of the nickname at the database level. This is nice because it ensures that there are no two subjects with the same nickname, which should never happen. This constraint is required in the new import script where I refer to subject foreign keys via their names. I just disabled this constraint and now this bug is fixed and the import script should work as long as there are no two subjects with the same nickname. I hope it won't break in the future...

**Comment by nsteinme** [comment]
So to clarify the problem was that the multiple subjects were both
"created" with a nickname of "-" and then got new nicknames later? Ok, I'll
leave it up to you and max to decide whether dropping the uniqueness
constraint to fix this is worth it.

**Comment by rossant** [comment]
Not exactly, I think django checked the uniqueness of the new values before alyx had a chance to change the nicknames (which happens *before* creating the subjects anyway).
