### ISSUE TITLE
weight plot tweaks

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#197]
In this one:
![image](https://cloud.githubusercontent.com/assets/7590975/24016131/e16706a4-0a82-11e7-94af-a2b07e29ac29.png)

it would be great if it could show at least two x-axis labels (currently there's no indication of scale??). And the place where the one point goes below the red line should result in some red. Also looks like the scheme in use on the sheets currently involved an intermediate level: red (<70%), pink (70%<w<75%), orange (75%<w<80%), see ALK044 sheet.

**Comment by rossant** [comment]
I don't understand your comment about the intermediate level in the scheme? There are only 2 colors: orange (<.8) or red (<.7)

**Comment by nsteinme** [comment]
Yeah it's fine let's skip that part right now, totally minor I just threw
it in with the same thought about plotting the red section and the time
scale (which are more important). Can explain more later if necessary.

**Comment by rossant** [comment]
Ah you were talking about the spreadsheets! OK for now I just implemented 2 colors.
The red one should have appeared but it didn't because there was a single point below the 70% threshold (so theoretically there is a rectangle with width 0...). In principle this bug is fixed now. The x scale bug should be fixed too.
