### ISSUE TITLE
collapsible sidebar or menu bar for "common" options? 

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#222]
So that you can quickly jump between common tables (subjects, weighings, etc) from any page. Is that kind of thing possible or easy?

**Comment by rossant** [comment]
Yes that's possible. A couple of suggestions:

* If there are no more than a few links, we could add them on the right in the "breadcrumbs" light blue bar at the top (aligned with "Home › Subjects › Subjects")
* Otherwise, we can add a dropdown menu at the same position, with an arbitrary number of links

**Comment by rossant** [comment]
Is it sufficient to have this option only on the "list" pages, not on the "add/change" pages? We can add it to both types of pages, at the expense of code duplication.

**Comment by rossant** [comment]
Done. I just added it on the list pages at the moment, let me know if that's not enough.

**Comment by nsteinme** [comment]
Either of those options would be good! On list, not on add/change is fine I
think.
