### ISSUE TITLE
Better way of marking stock/not stock

### ISSUE THREAD

**Issue by nippoo** [cortex-lab/alyx#224]
I think we can all agree that hardcoding "user__id == 5" everywhere is really Not Good. What happens if Charu leaves? (Also what if there are multiple lab technicians or if Charu has to look after specific peoples' mice if they leave the lab - etc - as separate from stock?)

Either we should do something a *leeeetle bit* nicer (like all userIDs >= 10000 are stock-holding users) or nicer still (mark stock-holding users with a flag in that table) or probably best, add a stock true/false bool in the Subjects table.

Thoughts?

**Comment by nippoo** [comment]
Anyway here's another example why the API is quite nice - I've now added the `?stock=True` flag in the API and when we change how this is stored in the backend we can just update the method and keep the same API call and syntax so it looks like nothing has changed...

**Comment by nsteinme** [comment]
Ok, so what we're trying to achieve is the following: 1) able to easily identify/filter what mice are in stock (so those who are concerned with maintaining stock don't get distracted/confused by all the mice that have already been taken out of it, and likewise for those who are looking into the stock for a new mouse they can use); 2) minimize amount of work/clicking that happens when a mouse is taken out of stock; 3) optimize/minimize what's shown in the Subjects list. And, do all this within the Admin interface.

Since you already at some point have to identify who is the new user of the mouse (no way around this, since it can be anyone), and since Charu is never the responsible_user for a procedured mouse, this is a quite reasonable and accurate proxy for which mice are in stock and which are not. Making this identification prevents you from having to update both the responsible_user and the is_stock boolean field (and prevents you from needing to have is_stock be a column in the already-crowded Subjects list). Furthermore, making the resp_user dropdown appear in the Subjects list makes it super-easy to find the correct stock mouse then just update this property, all in one go. 

Ideally you would have a form: the person selects which line they are interested in and they see a list of all mice in that line with positive zygosities. They click one, and it makes the current user the responsible user, makes the is_stock field false, and takes them to the mouse's overview page where they can edit the nickname and add a surgery. But we are not at the point of adding forms yet, we are instead trying to use the admin interface. So this is what we've got... 

It's possible I haven't thought of the best way to do it! Let me know. We can avoid "user_id==5" if we have a field in the settings that is something like "STOCK_HOLDER = charu" and then "auth_user.name==STOCK_HOLDER" or however you do it.

**Comment by nsteinme** [comment]
Re: API being nice here, yes definitely! noted.
