### ISSUE TITLE
Set up automatic backup

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#24]
Is it possible to export database contents to google sheets? @kdharris101 and I were discussing that we'd like to have a "test switchover" period in which people enter things into the database but it's automatically exported to a google sheet so we have a backup/fallback (that's the same as the old system) in case alyx goes down or something. 

More generally, we need to have a good backup scheme, of course, for when we start using it seriously. I suppose this sort of thing is standard.

**Comment by rossant** [comment]
Re: switchover period. We'll have to think about it. One simple possibility is "just" to have a backup (see below). Another one is to export stuff to google sheets automatically at every action, I'll have to check if that's possible.

Re: backup. There is an automatic export/import to JSON built into django that can be used as a backup. We could set up cron jobs to save them on a safe location. I think we should also have several other, independent, tested backup strategies using postgresql directly.

It would be good if @nippoo was also involved in setting up the various backup strategies before he leaves. It's not a trivial question. Have you heard of the [gitlab incident last week](https://techcrunch.com/2017/02/01/gitlab-suffers-major-backup-failure-after-data-deletion-incident/) (an alternative to github)? A tired developer accidentally ran `rm -rf` in a production postgresql folder and erased gigabytes of production data. They had 5 backup strategies. None had been well tested and none had worked. They lost 6 hours of data permanently impacting hundreds of users.

**Comment by nsteinme** [comment]
@kdharris101 @nippoo 

I think we're getting really close to entering into a live test. There's a lot to do yet for the restAPI, but that's secondary. The main parts for the live test - subject management/surgeries/manual parts - are really good. We will need to have a solid backup scheme before we do this, though. In addition to the above scheme(s) where we are exporting json backups that can be re-imported, I think we should also have a "psychologically safe" backup. What I mean here is a set of csv files (i.e. can open directly in excel) that contain the human-readable form of the data (i.e. using appropriate joins to eliminate UUIDs). That way we can show Matteo and Charu: look, just go to this folder at //zserver/Data/alyx-backups/2017-02-25/ and you can open any one of these csv files (subjects.csv, surgeries.csv, etc) and see all the information as it was yesterday - even though such-and-such crashed today or so-and-so accidentally wiped things today - just like if you'd been looking at our old google sheets. So it's safe to trust this, safe to enter data manually into it. 

I can generate these with a matlab program via the SQL queries. Then you (max, cyrille) could set up a cron thing to run it. Should I do this, or would you rather write an equivalent thing in python? Up to you. Either way I could send all the SQL queries if that's how you'd be implementing it.

**Comment by kdharris101** [comment]
Absolutely agreed on the need for a psychologically safe backup. Minor suggestions:


1.      Let’s use tab-delimited instead of comma delimited (because people sometimes type commas in text fields, screwing everything up, but rarely type tabs). Excel can read tab-delimited files.

2.      No need not to include UUIDs also, particularly if they come as the last columns in the field. Viewed with Excel, the field length will be truncated and you won’t see the whole thing. If they are the last columns in the file, they won’t matter either with a text editor. And if we have them, this will make it easier in the rare event that we actually needed to use these text files to recreate the database. (Unlikely but not impossible.)

**Comment by nsteinme** [comment]
Thanks Kenneth - tab delimited sounds fine, but let me make clearer the point about UUIDs. What you want is that your tab-delimited file says:

nickname    strain    species    cage    [etc]
Geronimo    B6;129    mouse    Ai95_C_3    [etc]
Herodotus    C57BL6/J    mouse    Vglut1_C_2    [etc]

rather than 

nickname    strain    species    cage    [etc]
Geronimo    owi1039uerqi    2398dwirwqer    12093lisdjfasd    [etc]
Herodotus    oeirq0123949    103294ulwdjkfa    fdkajr20912    [etc]

The latter version does indeed rebuild into the full database more easily - but that should be a separate version of the backup, not the "psychologically safe" version.

**Comment by kdharris101** [comment]
Yes, absolutely we want joins so all the information is human readable. What I meant was we could also include the UUID for the mouse (maybe other fields too) as the last columns of the psychologically safe file, where they will not do any harm, but might be useful just in case.

**Comment by nsteinme** [comment]
Right, sounds good!

**Comment by rossant** [comment]
Agreed with everything. To be clear, we're going to have two independent backup systems, one with the json dump from django, and one with your SQL queries that export to tsv?

For the tsv backup, I would suggest to write a bash script using [postgres](http://stackoverflow.com/questions/1517635/save-pl-pgsql-output-from-postgresql-to-a-csv-file/1517692#1517692) (see also the [documentation](https://www.postgresql.org/docs/current/static/sql-copy.html)) directly instead of matlab. For backups, the less dependencies, the better, I guess. Then we can run this script automatically everyday as a cron and save to `//zserver/Data/alyx-backups/2017-02-25/subjects.tsv` etc.

Is there another existing backup strategy for `//zserver/Data/` (which would contain the alyx backups)?

**Comment by nsteinme** [comment]
Great, I will write the SQL queries then try to get that postgres copy
thing to work, might ask you for help with that.

zserver is our main lab data server - it is cloned and exists in two
locations and also regularly backed up with history. I don't know all the
details, but it's the one thing we trust the most :)

**Comment by rossant** [comment]
Another really simple backup strategy is:

`pg_dump alyx | gzip > alyx.gz`

It's just a dump of the entire database, and it's one line to recover it if needed. Maybe we could have it as a third backup strategy if we want to be really really safe.

Something else we might want to do is an external independent system that checks every day that all backups have been properly performed. If some day the backup script fails, the cron will fail and we won't know about it. If a backup is missing, an email could be sent.

That's what the gitlab folks have failed to do. Their 5 backup strategies were all failing and they had no idea. That's how they lost production data. Better be safe than sorry.

**Comment by rossant** [comment]
TODO: export to google sheets
