### ISSUE TITLE
How to specify genotype as a string (inline model)

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#28]
A solution could be to specify it via a string instead, like `"GFP+; ROSA-WT+; AI95+/-"`

**Comment by nsteinme** [comment]
Can you clarify what "specify" means here? Are we talking about what the person manually entering the data has to do? In the current thing they have a dropdown to select the allele (like "AI95") and another dropdown to select the status of that one ("heterozygous",etc). Are you saying they should type that string instead? Otherwise I haven't understood.

**Comment by rossant** [comment]
That's right. We can keep it as it is in the Subject page. But when you're in the Cage page adding subjects, the forms for entering subjects are so-called "inlines" and as far as I understand, we can't have manytomany fields in there. The workaround is to just use a simple input text field where one manually enters the genotype.

**Comment by nsteinme** [comment]
Wouldn't we worry about what happens when someone puts in a typo? And would you be converting their text string into the current fields (so it would be searchable/sortable later)? And would they have to know which alleles were part of that line, or could they see it somewhere? I like the dropdowns thing a lot more....

**Comment by rossant** [comment]
In that case I don't know how to do it, let's wait for Max.

**Comment by rossant** [comment]
The alternative is that you can't set the genotype when adding subjects from a Cage or Litter page, you have to go to the individual subject page to do it.

**Comment by nippoo** [comment]
https://github.com/cortex-lab/alyx/commit/f0559cb6a0722c09f7d8b3cea5c095e0f217c214 has sort of done this maybe? @rossant ideally we should have some concatenated representation of all zygosities

**Comment by rossant** [comment]
Yes, something along the lines of `'; '.join(map(str, Subject.genotype.all()))`?
