### ISSUE TITLE
Disable non-secure http version of alyx

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#282]
@nippoo is it possible/desirable to disable the non-https version of alyx?

cc @kdharris101

**Comment by nippoo** [comment]
Yes this was already the case when I originally set it up with you but I commented out the relevant lines in /sites-enabled/.

The problem is that we're using LetsEncrypt for the HTTPS certificate, which is free, but it's not recognised as valid in the version of Java bundled with MATLAB it seems. Even though the latest Java now has the root certificates.

This should really be fixed before going public.

Two things need to happen:

- we need to fix this certificate issue, either by trusting the LE certificate in matlab or buying a 3-year certificate from Comodo and installing it on rod or whoever which is recognised for £20. I'd suggest the latter. https://github.com/cortex-lab/alyx-matlab/issues/8
- alyx-matlab needs to have https:// paths fixed (merge my PR which has a few other minor improvements! https://github.com/cortex-lab/alyx-matlab/pull/9)
- uncomment the lines in the config file and restart apache.

It is worth noting that this is a /breaking change/ if you haven't updated to the new alyx-matlab. Silently redirecting is not what you want, as you'll transfer your login details over the first unencrypted HTTP request (and it runs into other issues too).

Anyway I strongly recommend this is fixed before going into production. Get a paid SSL certificate for £20squids, test my PR, merge it, update all the computers, then uncomment the lines and restart apache.

**Comment by kdharris101** [comment]
I’m happy to buy an SSL certificate but could someone explain how to do it.

I went to comodo.com, there are lots of options, but couldn’t see one for £20 / 3 years.

**Comment by kdharris101** [comment]
GoDaddy seem to offer them from £54.99 / year.  https://uk.godaddy.com/web-security/ssl-certificate#sslplans

But I’m not sure which type we want. Any ideas?


From: Harris, Kenneth
Sent: 10 May 2017 17:45
To: 'cortex-lab/alyx' <reply@reply.github.com>; cortex-lab/alyx <alyx@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [cortex-lab/alyx] Disable non-secure http version of alyx (#282)

I’m happy to buy an SSL certificate but could someone explain how to do it.

I went to comodo.com, there are lots of options, but couldn’t see one for £20 / 3 years.

**Comment by rossant** [comment]
That one?

![image](https://cloud.githubusercontent.com/assets/1942359/25914583/163470ee-35bf-11e7-9e47-92c624946bf3.png)

**Comment by kdharris101** [comment]
Yes, that is what I was referring to. 

Is this what we need?

**Comment by rossant** [comment]
I think so, according to what Max said. Otherwise there are EssentialSSL Certificates from Comodo at 21$ per year: https://comodosslstore.com/promoads/cheap-comodo-ssl.aspx

**Comment by kdharris101** [comment]
Hi Matteo,

To have secure access to the amazon server from MATLAB, we need to buy an SSL certificate. GoDaddy sell them for £54.99 / year. They can be got cheaper from other vendors, but since we already have an account with them this might be simpler.

I believe this account is in your name, would it be possible to add one to our order with them? (Link is below).

ATB
k


From: Harris, Kenneth
Sent: 10 May 2017 18:16
To: 'cortex-lab/alyx' <reply@reply.github.com>; 'cortex-lab/alyx' <alyx@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [cortex-lab/alyx] Disable non-secure http version of alyx (#282)

GoDaddy seem to offer them from £54.99 / year.  https://uk.godaddy.com/web-security/ssl-certificate#sslplans

But I’m not sure which type we want. Any ideas?


From: Harris, Kenneth
Sent: 10 May 2017 17:45
To: 'cortex-lab/alyx' <reply@reply.github.com>; cortex-lab/alyx <alyx@noreply.github.com<mailto:alyx@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [cortex-lab/alyx] Disable non-secure http version of alyx (#282)

I’m happy to buy an SSL certificate but could someone explain how to do it.

I went to comodo.com, there are lots of options, but couldn’t see one for £20 / 3 years.

**Comment by rossant** [comment]
OK so we now have a SSL certificate from GoDaddy and I think we're ready to switch to https only and disable http. But we need to update MATLAB at the same time and let everyone know that http://alyx.cortexlab.net will no longer be available.

How do we proceed? @nsteinme do you want to merge the alyx-matlab PR and test it? Should we do it e.g. tomorrow morning?

https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority

**Comment by nsteinme** [comment]
I get an error trying to obtain a token from https://alyx.cortexlab.net
though it works with http://alyx.cortexlab.net. The error is
"javax.net.ssl.SSLHandshakeException:
sun.security.validator.ValidatorException ... unable to find valid
certification path to requested target."

Help me understand this Cyrille - this issue is about disabling the http
version, but can both http and https both be enabled side by side? Are they
not currently? If they can both work for a period, then that would be ideal
because I can test and then we can roll out the https version without any
interruption for those still using http. Let me know if I have this
wrong...

**Comment by rossant** [comment]
I think you're right we can first fix https and disable http later. I'll have a go and I'll let you know when you can try it in MATLAB.

**Comment by rossant** [comment]
OK can you try again?

**Comment by nsteinme** [comment]
Worked! :)

I have merged the https usage in alyx-matlab, then, but let's give it a few
days for everyone to get that code before disabling http.

**Comment by rossant** [comment]
done
