### ISSUE TITLE
re-assigned mouse at top of dropdown

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#283]
today charu and I passed a mouse back and forth to test the request system, I gave the mouse a nickname (TESTMOUSE) and then I reassigned it to Charu - now that mouse shows up at the top of the subjects dropdowns in surgeries and water restrictions even though it's not assigned to me anymore

**Comment by nsteinme** [comment]
This is because of the "remember most recent subject" feature that was
requested, and cyrille implemented. I think it's nice that it would keep it
there even if it's not your own subject - for instance imagine you're Laura
and you've just done a surgery for armin. So you scroll down through the
list of subjects once to find this subject when recording the surgery. But
then you want to add a weighing. Great not to have to scroll through again!
That one will be remembered when you go to the weighing page and show up at
the top.

If you were concerned that testmouse will always be there, it shouldn't -
try doing an action on another mouse and you'll see that one replace it, I
think.

**Comment by petersaj** [comment]
ok fine with whatever you guys want, I'd just think for most people that only work with a handful of their own mice it'd be easier to visually parse if your animals were always listed alphabetically in the drop down

**Comment by nsteinme** [comment]
@rossant do you remember which issue requested this feature? I think it was
from Julie or Laura but I can't find it. In any case, it would be good for
Andy to discuss with the person who requested so they can decide what the
best solution is.

**Comment by rossant** [comment]
I can't find it either. I think it was Laura?

**Comment by rossant** [comment]
OK let me know what the final decision is here

**Comment by rossant** [comment]
@nsteinme @petersaj please let me know when you have reached a decision. Thanks!

**Comment by petersaj** [comment]
up to you @nsteinme, for my purposes I'd probably only ever want to see my mice at the top, but then again I'd probably never reassign mice away from myself so wouldn't run into this

**Comment by nsteinme** [comment]
I guess I vote we leave it alone then - one extra mouse appearing at the top in the rare case of assigning-away isn't likely to break anyone, but it could be a really helpful feature to have in other cases when you're doing multiple things for someone else's mouse.
