### ISSUE TITLE
add water restriction has non-related things on page

### ISSUE THREAD

**Issue by petersaj** [cortex-lab/alyx#284]
when adding a new water restriction there are the same fields as for a surgery - shouldn't this just be start date, end date, reference weight?

**Comment by nsteinme** [comment]
Yes, we can talk about this at the meeting in a couple hours. The reason is
that we have a basic "action" class that both surgeries and water
restrictions inherit these fields from. We could reconsider that idea if it
seems problematic. Agreed that it seems a bit silly for water restrictions,
though perhaps I'd vote it's nice to keep at least "users" and "narrative",
for instance.

**Comment by rossant** [comment]
What's the decision here?

**Comment by rossant** [comment]
@nsteinme @petersaj please let me know when you have reached a decision. Thanks!

**Comment by petersaj** [comment]
@nsteinme I think would be cleaner if the extra fields went away but if it'd make things weird with having separate classes of actions then doesn't really matter

**Comment by nsteinme** [comment]
Can we just hide "location" and "procedures" fields on the add water
restriction page, is that an option?

**Comment by rossant** [comment]
Sure, it's easy to customize the fields in any view, even those than inherit a parent view.
