### ISSUE TITLE
File storage locations

### ISSUE THREAD

**Issue by kdharris101** [cortex-lab/alyx#327]
Hi there, 

@peterzh and I are having a discussion, and have a question for the larger group.

Should Alyx decide where files are stored on zserver? When you run the code to register a file, should Alyx provide a suggested location to save it in using back-end code? Or should should this be done on the front end?

**Comment by rossant** [comment]
Personally I don't think alyx should make a decision about the location of files. It should be the responsibility of the different programs. The programs tell alyx where they put the files.

**Comment by nsteinme** [comment]
It is at least easier to transition if we let programs decide where to
store things - that way all existing programs and code can continue to
function normally.

**Comment by nippoo** [comment]
The solution we'd previously come up with was to have an endpoint that would give you a recommended filepath for your new dataset. Of course you're free to override it (or existing programs can ignore that endpoint and just set their own filepath as before) but eventually programs should transition to using alyx's path rather than the `dat` package's so it makes things easier to change at short notice (if we suddenly need to buy a high-performance storage array for some types of data then we can very easily set that centrally)

**Comment by kdharris101** [comment]
This sounds like a good plan.

There might be some future circumstances where we want to use a recommended filepath. So why don’t we include this as a potential output argument, but leave it blank for now, and have the local software decide. That keeps our options open for the future.

ATB
k
