### ISSUE TITLE
deploy daily reports

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#346]
i.e. start sending them. Could first just enable it for me and @charureddy if you like, up to you.

**Comment by rossant** [comment]
can you give me the exact `manage.py report` command that you would like to activate for now? You can test with `--no-email` first. Then it's just a matter of adding this command to the crontab on cone.

**Comment by nsteinme** [comment]
Ok, let's fix the features/bugs that I raised but then it'll be: 

For non-stock managers:
python manage.py report water_restriction surgery past_changes 

For stock managers:
python manage.py report water_restriction surgery past_changes todo

Looking good! I think people will find this useful.

**Comment by nsteinme** [comment]
Hey, so want to try turning this on today using alyx-dev, then if it goes out well to me and @charureddy tomorrow and Monday, we can then turn it on for everyone after the code update happens on monday morning on alyx?

**Comment by rossant** [comment]
Sure, is there anything that remains to be done in the implementation or is it all working? If it works, can you try setting up the cron job yourself so that you get a feeling of how it works? Here are the instructions:

* `ssh cone`
* `crontab -l` to see the list of jobs    
* `crontab -e` to edit the jobs
* The jobs are executed with the `ubuntu` user
* Every line represents a job that is run periodically. The first 5 characters specify when and how often the job executes
* You can take inspiration from the existing commands for backup
* I suggest creating one (or several) bash script in `/var/www/alyx-dev` containing the command(s) you want to run periodically for the reports
* Don't forget to source activate alyx or alyx-dev in the bash script
* As you can see, *all* paths and executables must be absolute (not relative) in the crontab
* I suggest outputing stdout/sterr to a specific file like `/var/log/alyx_report.log`
* To test, you can replace the first 2 characters  of the crontab line (minutes and hours) to `* *`. As soon as you save and exit in `crontab -e`, the command will run instantly and you can see if it worked. Be careful because that command will run *every minute*  until you edit the line again.

Let me know if you have any issue.

**Comment by nsteinme** [comment]
Hey Cyrille, thanks for these detailed instructions. I think I almost got
the first one working. It successfully outputs all the stuff to the
alyx_reports.log file and says "email sent" to me. However, I don't get the
email. I wonder whether it might be related to the fact that I kept getting
an error on "source activate alyx" - is there a path to this "source"
command that I need to use? I tried "whereis source" but it doesn't show me
anything. Let me know - if I can get this one running then yeah I'll put in
place the other ones too.

**Comment by rossant** [comment]
I think it must be something along the lines of
source /var/www/alyx-dev/alyx-dev/bin/activate
I'll check tonight

**Comment by rossant** [comment]
Fixed -- the email settings were set for alyx but not alyx-dev. Anyway now I think you can move the script to alyx instead of alyx-dev and deploy the reports.

**Comment by nsteinme** [comment]
Ah, I should have thought of that. Ok, thanks, will do.

**Comment by rossant** [comment]
@nsteinme what's the status of this?

**Comment by nsteinme** [comment]
Yeah, really sorry for letting this slide. It seemed to work (at least from my perspective) for the last two "first of the month" runs, so I've changed it to send M-F. Let's consider it deployed for now and open other issues if there are problems with it. Thanks!!
