### ISSUE TITLE
Error downloading data

### ISSUE THREAD

**Issue by MandanaAhmadi** [cortex-lab/alyx#542]
I download data through one using matlab. However, I get an error for downloading data for some sessions for some mice (e.g., IBL-T4 on 2019 4 25). And sometimes it downloads empty files (e.g.,April 10 for IBL_10). Do we know what's happening?

**Comment by oliche** [comment]
This should be in https://github.com/int-brain-lab/ibllib/issues

So in one case I've added a warning to make sure it lets you know when there is a file registered but the file hasn't made it to the server.
In the other case the issue was Json conversion to structure returns scalars if there is only one object, not a cell.

All of this is in the ibllib dev branch, or in the next release.
