### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by oliche** [cortex-lab/alyx#615]
TO handle permissions on a subject basis, add a many-to-many field in the Subjects table to the LabMembers.
Permissions to edit/modify subject related records can be granted to any labmember by the responsible user.

**Comment by rossant** [comment]
if the new field empty => only the responsible user can edit the subject

**Comment by rossant** [comment]
@petersaj to fix the permissions issues, one discussed solution is to let anyone add another user to a mouse's "allowed users". So if you want to close a water restriction, you need to have the mouse's responsible user add you to the mouse's allowed users. But this would have to be done on a mouse per mouse basis which is not terribly convenient.

Another solution would be to have the "allowed users" field to be on a lab member basis, so that it would automatically apply to all mice of that member. What do you think?

More generally we'd prefer a solution like this where everyone controls who can do what, rather than implementing ad-hoc rules in the code which is more fragile and less extendable.

**Comment by sfailor** [comment]
Users can already add water restrictions to a mouse that they are not responsible for. However, users that are responsible for a mouse cannot end a water restriction if another user started it. If it was the case that only users responsible for a given mouse could add water restrictions this wouldn't be an issue, but would, of course, be less convenient for those training other users' mice.

**Comment by petersaj** [comment]
I thought from the email chain with Charu at the end of November that the solution was going to be making all objects editable by anyone for all non-stock mice? This seems good to me - I don't think anything needs to be locked because all edits will be legitimate
