### ISSUE TITLE
on creating a breeding pair, alyx doesn't like the parents

### ISSUE THREAD

**Issue by mauricev** [cortex-lab/alyx#637]
Add a breeding pair. Name the pair and supply a father and a mother (by the way, the lists ignore the gender, allowing one to put a female in the father field and a male in the mother field) and then click Save. 
It fails with the complaint,

_Select a valid choice. That choice is not one of the available choices._

This is odd because the only entry we can put in these fields are ones already in the database. It's as if alyx isn't aware we entered anything.

This was tested using the build with the latest commit, #636.

**Comment by oliche** [comment]
I can reproduce the problem here, it comes from the fact that the lists proposes subjects as parents that are not validated afterwards.
The reason could be that a Mother or Father has the wrong gender, and/or the responsible user for the subjects chosen as parents should be set as stock managers.

This needs 
1) to filter the listboxes only to subjects that will allow the form to be validated (ie. proper gender and responsible user)
2) send a more useful error message
