### ISSUE TITLE
Weighing plot

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#64]

**Comment by nsteinme** [comment]
There's currently no plot at all, right? I don't see it. Was just checking because we had a good suggestion for how this plot should look, so I'll add that suggestion here:

- Plot weight over time from the first weighing to the most recent
- Also plot the "70% weight" and "80% weight" over time - the latter of these is exactly what you call "thresh_weight" in the water_requirement_total function, but compute it for every date between first weighing and today. "70% weight" is same thing but 0.7*expected_weight_today. These two traces are red (70%) and orange (80%). 
- Ideally, it would be really cool to then indicate even more obviously when the mouse's weight is too low, and the specific suggestion was to highlight the parts of the plot when the mouse is below weight, like here, but maybe with some less-terrible choice of colors:
![image](https://cloud.githubusercontent.com/assets/7590975/23953562/dedcaa7a-098c-11e7-9cc9-cd1794b67d5f.png)

**Comment by rossant** [comment]
A basic plot with just the weighings already exists but there is a bug right now. It should be fixed so if you restart the server it should work.

**Comment by rossant** [comment]
Would it be possible to import the weighing and maybe water admin/restriction data as part of the import script? Otherwise I can just generate random data. I need data for developing this.

**Comment by nsteinme** [comment]
Great, very nice, yes I can see the weighing plot now! See other issue for
info about importing water/weighings data.
