### ISSUE TITLE
add subjects and litters to cages from the cage page

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/alyx#7]

**Comment by rossant** [comment]
For technical reasons, if you want to display all litters belonging to a cage, the litter needs to have a `ForeignKey` to `Cage`, which is not the case currently. In theory, a litter has a mother and a father, and those do have a Cage, so we shouldn't need to have this duplicate information, but this relationship is indirect. Django requires direct relationships in order to display a list of related items in an "add/change" admin page.

The same applies to other cases where you want to list indirectly-related items.

**Comment by rossant** [comment]
To be clear do you want to

1. see all subjects and litters in a cage
2. add a new subject or litter from a "cage" page
3. both

?

**Comment by nsteinme** [comment]
Yes, both of those.

The reason not to add the cage key to the litter is the following: while
the litter is originally born and all housed in one particular cage, the
mice in that litter will eventually go off into different cages. But they
are always part of the litter, which is about the parental/filial
relationships.

So let's leave the cage foreignkey out of the litter.

Then we make these compromises:
1) Don't list the litters on a cage page. Do list all the subjects, and in
the table, show the litter to which those subjects belong.
2) Don't add a litter *to* the cage, however do be able to make a new
litter with the mother and father from some particular cage autofilled. If
that's not possible or not easy, then let's leave it for now and worry
about it later - it may not be totally critical, we can test without it
first and see how it goes.

For clarity (with some redundancy), do keep:
A) See all subjects in a cage from the cage page
B) add a new subject to a cage from the cage page

**Comment by rossant** [comment]
OK, looks good. Done (not 2 yet, might not be easily doable).
