### ISSUE TITLE
misc_labmember.is_public_user does not exist 

### ISSUE THREAD

**Issue by mayofaulkner** [cortex-lab/alyx#740]
I am trying to run tests on my local alyx instance but running into the following error when setting up the test db

```
django.db.utils.ProgrammingError: column misc_labmember.is_public_user does not exist
LINE 1: ...ember"."id", "misc_labmember"."is_stock_manager", "misc_labm...
```

**Comment by oliche** [comment]
This is due to the auth model change during the project and particularly to this migration:
https://github.com/cortex-lab/alyx/blob/e649b39cd3359115651035030f369b6b5f288378/alyx/misc/migrations/0010_labmember_is_public_user.py

The solution for blank slate databases or migrated databases is currently implemented in this commit, on the `docs` branch.
https://github.com/cortex-lab/alyx/commit/e2c968301a893efe8bede4c93bd5b4d92d46f4c0

We will switch to this once all of the known databases are migrated !
